export const data = {
    indkøb: [
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 100,
        Beløb: 2000,
        Tidsperiode: "2024-05",
        Hospital: "Nordsjællands Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 300,
        Beløb: 3000,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 2200,
        Beløb: 15000,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat a",
        Antal: 100,
        Beløb: 2000,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 2",
      },
      
  
  
  
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "akut",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "akut",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 100,
        Beløb: 2000,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 300,
        Beløb: 3000,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "akut",
        Afsnit: "Afsnit 2",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 2200,
        Beløb: 15000,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat a",
        Antal: 100,
        Beløb: 2000,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "akut",
        Afsnit: "Afsnit 2",
      },
        
      
      
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 200,
        Beløb: 5000,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 100,
        Beløb: 2000,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 300,
        Beløb: 3000,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 2200,
        Beløb: 15000,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat a",
        Antal: 100,
        Beløb: 2000,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 2",
      },
    ],
  
  
  
  
    forbrug: [
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 50,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 20,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 22,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 14,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 20,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 1566,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 3",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat a",
        Antal: 1,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 4",
      },
      
  
  
  
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 25,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 20,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 10,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 52,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 50,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 400,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat a",
        Antal: 34,
        Tidsperiode: "2024-05",
        Hospital: "Bispebjerg Hospital",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 2",
      },
        
      
      
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 26,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 27,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 20,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 10,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 112,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat b",
        Antal: 412,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 1",
      },
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat a",
        Antal: 123,
        Tidsperiode: "2024-05",
        Hospital: "Herlev hospital",
        Afdeling: "kronisk",
        Afsnit: "Afsnit 2",
      },
    ],
    kassation: [
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 50,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 4",
      },
      // Tilføj flere kasseringsposter her
    ],
    lagerbeholdning: [
      {
        DatoPrintet: "2024-05-03",
        Medicin: "Præparat A",
        Antal: 30,
        Tidsperiode: "2024-05",
        Hospital: "Rigshospitalet",
        Afdeling: "Medicinsk Afdeling",
        Afsnit: "Afsnit 1",
      },
      // Tilføj flere lagerbeholdningsposter her
    ],
    hospitaler: [
      {
        Navn: "Rigshospitalet",
        Afdelinger: [
          {
            Navn: "Medicinsk Afdeling",
            Afsnit: ["Afsnit 1", "Afsnit 2"],
          },
          {
            Navn: "kronisk",
            Afsnit: ["Afsnit 3", "Afsnit 4"],
          },
          // Tilføj flere afdelinger for Rigshospitalet her
        ],
      },
      {
        Navn: "herlev",
        Afdelinger: [
          {
            Navn: "Medicinsk Afdeling",
            Afsnit: ["Afsnit 1", "Afsnit 2"],
          },
          {
            Navn: "Pædiatrisk Afdeling",
            Afsnit: ["Afsnit 3", "Afsnit 4"],
          },
          // Tilføj flere afdelinger for Rigshospitalet2 her
        ],
      },
      {
        Navn: "Bispebjerg Hospital",
        Afdelinger: [
          {
            Navn: "Medicinsk Afdeling",
            Afsnit: ["Afsnit 1", "Afsnit 2"],
          },
          // Tilføj flere afdelinger for Bispebjerg Hospital her
        ],
      },
      {
        Navn: "Bispebjerg Hospital",
        Afdelinger: [
          {
            Navn: "akut",
            Afsnit: ["Afsnit 3", "Afsnit 4"],
          },
          // Tilføj flere afdelinger for Bispebjerg Hospital her
        ],
      },
      {
        Navn: "Nordsjællands Hospital",
        Afdelinger: [
          {
            Navn: "Hjerteafdelingen",
            Afsnit: ["Afsnit 1", "Afsnit 2", "Afsnit 3"],
          },
          {
            Navn: "Lungeafdelingen",
            Afsnit: ["Afsnit 1", "Afsnit 2", "Afsnit 3"],
          },
          // Tilføj flere afdelinger for Nordsjællands Hospital her
        ],
      },
      // Tilføj flere hospitaler her
    ],
  };